### ISSUE TITLE
Metrics API missing

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/avalanche.js#39]
I also noticed that the Metrics API is not present in Slopes . (https://docs.ava.network/v1.0/en/api/metrics/)

Gecko produce the Metrics as a 'Prometheus compatible metrics' .

I propose that we create an endpoint that return the metrics either "raw" (prometheus style) or as a JSON (I'm using this in Snowboard : https://www.npmjs.com/package/parse-prometheus-text-format) .

What do you think ?

**Comment by collincusce** [comment]
Thanks! Assigned to @cgcardona

**Comment by cgcardona** [comment]
Circling back to this—it seems like the best option for now is to just return "raw" (prometheus style) . Later we can reevaluate adding a 3rd party lib and/or parsing and formatting them ourselves.

**Comment by cgcardona** [comment]
Resolved in https://github.com/ava-labs/avalanche.js/pull/46
