### ISSUE TITLE
Issue with BN in Slopes

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/avalanche.js#45]
I stumbled upon an annoying bug .

When calling `exportAVA` from the PlatformAPI , you need to provide 3 params : 

- `to`
- `nonce`
- `amount` , which need to be passed as a BN in Slopes .

My issue is with this `amount` .

I'm doing the following : 

```
 const txId = await api.Platform().exportAVA(new BN(data.amount), data.to.substring(2,data.to.length), data.nonce);

```

where `data.amount` is equal to 10 .

Am expecting to see in my network tab a call to platform.exportAVA with 10 in request param for amount but ... I see : 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/29312251/84934146-36ad3680-b0d7-11ea-8ceb-3d3c187af496.png">

I did put some logs in Slopes to see what the heck is happening. 
It seems that the params that are passed to the `callMethod` are at one point converted to a string via ` JSON.stringify(rpc)`, and looks like it transform the BN that have a value of '10' to this '0a' value .

See : 

```typescript
export class JRPCAPI extends APIBase {
    protected jrpcVersion:string = "2.0";
    protected rpcid = 1;
    callMethod = async (method:string, params?:Array<object> | object, baseurl?:string):Promise<RequestResponseData> => {
		...
		...		
        return this.core.post(ep, {}, JSON.stringify(rpc), headers,
		...
```

This JSON.stringify(rpc) give something like : 

```json
{"id":2,"method":"platform.exportAVA","params":{"to":"AwnMtRHWF7rYZm8x7VkRdTLnZUoboitRe","amount":"0a","payerNonce":3},"jsonrpc":"2.0"}
```
I would expect `10` in place of `0a` there : )

Am I missing something there ?

**Comment by collincusce** [comment]
Yuuuup that's a bug. @cgcardona wanna get this one?

**Comment by cgcardona** [comment]
Confirmed
