### ISSUE TITLE
Metrics API - Issue while using it in browser

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/avalanche.js#54]
I have an issue with the Metrics API .

In short, it works well in a nodeJS app, but not when used in a Vue app (response is always empty) . I believe it is because of the `responseType` set in `AxiosRequestConfig` . It is set to `json` all the time, but in fact the `/ext/metrics` api is returning : 

<img width="357" alt="image" src="https://user-images.githubusercontent.com/29312251/88452634-a0e89200-ce60-11ea-8a06-80417ddc4629.png">

I guess my browsers (tested in chrome and firefox) does not like this and somehow 'protect' me by blocking the response . 

I did a small experiment, modifying the AxiosRequestConfig in types.ts (replaced `reponseType : json` by : 
```
    const axConf:AxiosRequestConfig = {
      baseURL: `${this.core.getProtocol()}://${this.core.getIP()}:${this.core.getPort()}`,
      responseType: 'text',
    };
```

in Avalanche , ran it locally and tadaaaa I got a response with all metrics .

**Comment by collincusce** [comment]
@cgcardona confirm this is fixed in a future release on development branch?

**Comment by cgcardona** [comment]
Confirmed. I'll check it out.

**Comment by collincusce** [comment]
Hey @cgcardona did you confirm this issue is fixed, or was I mistaken?

**Comment by collincusce** [comment]
@cgcardona any updates?

**Comment by collincusce** [comment]
Should be rolled into the next release through PR https://github.com/ava-labs/avalanche.js/pull/92
