### ISSUE TITLE
SelectTxClass: unknown txtype 4

### ISSUE THREAD

**Issue by ang-st** [ava-labs/avalanche.js#57]
Hi,
I'm using avalanche.js to stream data from ipc socket and got this exception

```
/app/node_modules/avalanche/typings/src/apis/avm/tx.js:502
    throw new Error(`Error - SelectTxClass: unknown txtype ${txtype}`);
    ^

Error: Error - SelectTxClass: unknown txtype 4
    at Object.exports.SelectTxClass (/app/node_modules/avalanche/typings/src/apis/avm/tx.js:502:11)
    at UnsignedTx.fromBuffer (/app/node_modules/avalanche/typings/src/apis/avm/tx.js:368:36)
    at Tx.fromBuffer (/app/node_modules/avalanche/typings/src/apis/avm/tx.js:422:34)
```

while i will `try..catch` as i probably don't need it for now, i was wondering what are `Type 4` transactions and if it will supported by avalanche.js ? 

Bests

**Comment by collincusce** [comment]
When doing a cross-chain swap, there's export and import methods. Each of those methods produce a transaction that is sent to the network. Those Tx's are not yet implemented in Avalanche.js, but they absolutely should be. Until they are, please handle this in your code. We'll be working out a spec for those unhandled transaction types soon.

**Comment by collincusce** [comment]
A fix for this will be in https://github.com/ava-labs/avalanche.js/pull/65

This fix will only work on Everest release, however, as the API call necessary to get the import UTXOs isn't implemented in Denali releases.

**Comment by collincusce** [comment]
completed in everest release, ready for push
