### ISSUE TITLE
Properly handle  the `locktime` which is passed in to `avm.buildCreateAssetTx`

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche.js#71]
The `locktime` which is being passed in to [buildCreateAssetTx](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/avm/api.ts#L871-L893) isn't being handled. 

We can pass `locktime` to `utxoset. buildCreateAssetTx ` like we do with  `utxoset.buildCreateNFTAssetTx ` below in [buildCreateNFTAssetTx](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/avm/api.ts#L943-L962)

**Comment by collincusce** [comment]
what branch? I'm presently revising all of this on the tx-fees branch
