### ISSUE TITLE
Remove deprecated functionality before mainnet

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche.js#72]
Mainnet is a good opportunity to sunset and remove the following known deprecated functionality.

## Deprecated

* [keychain.signTx](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/avm/keychain.ts#L237-L245)

**Comment by collincusce** [comment]
Speaking with @cgcardona he means to say that the Duplicate functions need to be removed from Admin as they were placed into Info.

**Comment by collincusce** [comment]
Asked for the Duplicate stuff to be split into a separated issue.

**Comment by cgcardona** [comment]
Duplicate functionality moved to https://github.com/ava-labs/avalanche.js/issues/73

**Comment by collincusce** [comment]
sneaking into tx-fees

**Comment by collincusce** [comment]
completed
