### ISSUE TITLE
Remove duplicate functionality before mainnet 

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche.js#73]
Mainnet is a good opportunity to remove the following known duplicate functionality.

The methods have been removed from gecko's Admin service and are only in it's Info service.

## Duplicate

* [getNodeID](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/admin/api.ts#L22)
* [getNetworkID](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/admin/api.ts#L33)
* [getBlockchainID](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/admin/api.ts#L84)
* [getNodeVersion](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/admin/api.ts#L97)
* [getNetworkName](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/admin/api.ts#L105)
* [peers](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/admin/api.ts#L143)

**Comment by collincusce** [comment]
sneaking into tx-fees

**Comment by collincusce** [comment]
completed
