### ISSUE TITLE
Remove filenames from admin RPC calls

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche.js#77]
The following path and file names are now hardcoded in gecko

* `cpuProfileFile`
* `memProfileFile`
* `lockProfileFile`

They have also been removed from their respective RPC calls. 

We need to remove the following

* `filename` from [startCPUProfiler](https://docs.avax.network/v1.0/en/tools/avalanche.js/api/classes/adminapi.adminapi-1/#startcpuprofiler)
* `filename` from [memoryProfile](https://docs.avax.network/v1.0/en/tools/avalanche.js/api/classes/adminapi.adminapi-1/#memoryprofile)
* `filename` from [lockProfile](https://docs.avax.network/v1.0/en/tools/avalanche.js/api/classes/adminapi.adminapi-1/#lockprofile)

**Comment by collincusce** [comment]
easy fix, sneaking it into tx-fees.
