### ISSUE TITLE
Add new PlatformVM RPC endpoints

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche.js#80]
Add each of the following new Gecko PlatformVM RPC endpoints to [API-PlatformVM](https://github.com/ava-labs/avalanche.js/blob/development/src/apis/platformvm/api.ts)

* `platform.getTx`
* `platform.getTxStatus`

**Comment by collincusce** [comment]
completed in 

https://github.com/ava-labs/avalanche.js/commit/62e2a6313aec444c67b4d39b0c093d95690f8110
