### ISSUE TITLE
keyChain.importKey should return KeyPair

### ISSUE THREAD

**Issue by kanatliemre** [ava-labs/avalanche.js#81]
Instead of returning an address, this function should return the key pair created.

**Comment by collincusce** [comment]
It's so obvious! And great! I'm doing it. Now.

**Comment by collincusce** [comment]
makeKey too

**Comment by collincusce** [comment]
completed in https://github.com/ava-labs/avalanche.js/commit/73ab673494536e28f99cf8b4f00dfb09d5221913
