### ISSUE TITLE
Can't load avalanche.js in code sandbox

### ISSUE THREAD

**Issue by harryEth** [ava-labs/avalanche.js#89]
I have an issue with using avalanche.js in the code sandbox. when I import avalanche.js in code sandbox, `Could not find module in path: 'avalanche' relative to '/src/App.js'` error shows up. 

![image](https://user-images.githubusercontent.com/33265609/91706995-0b61b180-eb34-11ea-94a2-1a5249927436.png)

code example:

![image](https://user-images.githubusercontent.com/33265609/91707498-bbcfb580-eb34-11ea-8eb1-1697fd6f5cbe.png)

anyone can help with this?

**Comment by collincusce** [comment]
What is code sandbox?

**Comment by kanatliemre** [comment]
![Screen Shot 2020-09-07 at 8 31 21 PM](https://user-images.githubusercontent.com/14934754/92421944-19718c80-f149-11ea-8938-58f7b3f1837e.png)

Have you added avalanche as a dependency?

**Comment by harryEth** [comment]
> ![Screen Shot 2020-09-07 at 8 31 21 PM](https://user-images.githubusercontent.com/14934754/92421944-19718c80-f149-11ea-8938-58f7b3f1837e.png)
> 
> Have you added avalanche as a dependency?

yes, of course. can you check here? https://codesandbox.io/s/github/MagicLabs/example-avalanche

it works well on the local development, but not in the code sandbox.

**Comment by collincusce** [comment]
I'm not sure. I have never heard of "codesandbox.io" but this looks like a third party application that can't handle...something... but Avalanche.js is fine. For instance, our wallet works just fine in VSCode and when compiled, but put it in codesandbox.io and it flips out.

https://codesandbox.io/s/strange-wildflower-qnzwr

My advice is to file a ticket with the codesandbox.io folks to figure out what they're missing on their end. If they have information for us, I'll be receptive, but unless it's a standard we're missing, we're not likely to change.
